nttcom/terraform-provider-ecl

- ecl/data_source_ecl_network_port_v2.go
- ecl/resource_ecl_network_port_v2.go
I forgot to `go fmt` before initial commit.
This is refactoring commit.
> refactor by go fmt around port

- ecl/data_source_ecl_network_port_v2.go
- ecl/data_source_ecl_network_port_v2_test.go
- website/docs/d/network_port_v2.html.markdown
This pull request mainly fixes followings
- Fix schema of SegmentationType from Int to String
- Remove useless parameters as data source query
- Fix documents according to above changes
- Fix some typos
> Fix port datasource

- ecl/data_source_ecl_network_port_v2_test.go
DeviceID property of port is determined when some resource
is connected to the port.
But in current device id test, nothing will be attached,
so in all test execution, device_id is actually set as blank string.
This means that if some other port exists in same tenant,
all of test execution turns to be failed.
So I fixed test case as followings.
- Create subnet in test
- Create instance with fixed ip
Then port.device_id will be set with the ID of instance,
so test will be work expectedly.
> Fix device_id test case

- ecl/resource_ecl_network_network_v2_test.go
testing.go:568: Step 0 error: /var/folders/f3/s1j4kqx17cz3rdcmj0m004pr0000gn/T/tf-test288583067/main.tf:21,5-6: Invalid argument name; Argument names must not be quoted.
And fix relevant indents.
> Resolved following error

- README.md
- ecl/config.go
- ecl/import_ecl_rca_user_v1_test.go
- ecl/provider.go
- ecl/resource_ecl_rca_user_v1.go
- ecl/resource_ecl_rca_user_v1_test.go
- go.mod
- go.sum
- website/docs/r/rca_user_v1.html.markdown
- website/ecl.erb
Add remote console access user resource.
> Support remote console access

- ecl/data_source_ecl_imagestorages_image_v2_test.go
- ecl/resource_ecl_imagestorages_image_v2_test.go
- ecl/resource_ecl_imagestorages_member_accepter_v2_test.go
- Indentation
- Definition of Map to apply HCL2
> Fix test case

- CHANGELOG.md
Refine changelog in reference to aws provider.
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md
> Refine changelog

- ecl/resource_ecl_rca_user_v1_test.go
Assign a randomly-generated user name for RCA User Resource to make parallelize test possible.
> Parallelize test for TestAccRCAV1User_basic

- ecl/import_ecl_rca_user_v1_test.go
- ecl/resource_ecl_rca_user_v1_test.go
Add resourceName, resourcePath generate functions
so that import test can read correct resourcePath
from basic config
> Fix import test for RCA User

- ecl/resource_ecl_compute_volume_v2.go
- ecl/resource_ecl_compute_volume_v2_test.go
- add image_name parameter
- add test case
- to use image_name
- to use both image_id and image_name
> fix volume resource to enable image_name

- ecl/resource_ecl_provider_connectivity_tenant_connection_v2_test.go
TestAccProviderConnectivityV2TenantConnection_NotSpecifyDeviceInterfaceID AccTest Typo was modified.
> Fixed ExpectError message

- ecl/resource_ecl_provider_connectivity_tenant_connection_v2_test.go
* Only Data plane network can be attached to tenant connection
* Tenant connection request should be depend on virtual network appliance (vna) because it takes time to make vna COMPLETE
> IF-4680 Fix tenant connection AccTest

- ecl/resource_ecl_compute_instance_v2.go
- go.mod
- go.sum
This PR adds cloud_drive attribute to allow some OS to perform cloud-init operations.
> Adds cloud_drive attribute.

- ecl/resource_ecl_compute_instance_v2_test.go
Added test case for config_drive attribute added in https://github.com/nttcom/terraform-provider-ecl/pull/60.
> Added config_drive Testcase.

- ecl/data_source_ecl_network_fic_gateway_v2.go
- ecl/data_source_ecl_network_fic_gateway_v2_mock_test.go
- ecl/data_source_ecl_network_fic_gateway_v2_test.go
- ecl/data_source_ecl_network_internet_gateway_v2_mock_test.go
- ecl/data_source_ecl_network_internet_service_v2_mock_test.go
- ecl/data_source_ecl_network_internet_service_v2_test.go
- ecl/provider.go
- ecl/provider_test.go
- website/docs/d/network_fic_gateway_v2.html.markdown
- website/ecl.erb
Change request string from capital to small.
Add mock request api in Internet Gateway.
> ysssasaki_IF-4909_support_FIC_Gateway

- ecl/data_source_ecl_network_qos_options_v2.go
- ecl/data_source_ecl_network_qos_options_v2_mock_test.go
- ecl/data_source_ecl_network_qos_options_v2_test.go
- ecl/provider.go
- website/docs/d/network_qos_options_v2.html.markdown
This PR adds qos_options data_source.
> Support qos_options in data source

- ecl/resource_ecl_vna_appliance_v1.go
* ecl/resource_ecl_vna_appliance_v1.go
- 保秘のため passwordに Sensitve指定を追加した
> :sparkles: IF-8191 Add Sensitive Member for Password of VNA

- website/docs/index.html.markdown
* website/docs/index.html.markdown
- 見出し"Example Usage"について記述 "tenant_name"を "tenant_id"に修正
> :books: IF-10136 Fix to tenant_id from tenant_name

- ecl/resource_ecl_imagestorages_image_v2.go
- ecl/resource_ecl_imagestorages_image_v2_test.go
- go.mod
- go.sum
- vendor/github.com/nttcom/eclcloud/v2/ecl/imagestorage/v2/images/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/imagestorage/v2/images/results.go
- vendor/modules.txt
- website/docs/r/imagestorages_image_v2.html.markdown
Delete the license switch.
- Change eclcloud version to v2.5.0
- go.mod
- go.sum
- vendor/modules.txt
- Delete license switch.
- ecl/resource_ecl_imagestorages_image_v2.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/imagestorage/v2/images/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/imagestorage/v2/images/results.go
- website/docs/r/imagestorages_image_v2.html.markdown
- Remove Acceptance Test related to license switch.
- ecl/resource_ecl_imagestorages_image_v2_test.go
> IF-10688 Delete License Switch

- go.mod
- go.sum
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/certificates/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/health_monitors/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/health_monitors/results.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/listeners/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/listeners/results.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/load_balancers/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/load_balancers/results.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/operations/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/plans/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/policies/doc.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/policies/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/policies/results.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/routes/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/routes/results.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/rules/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/rules/results.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/system_updates/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/target_groups/requests.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/target_groups/results.go
- vendor/github.com/nttcom/eclcloud/v2/ecl/managed_load_balancer/v1/tls_policies/requests.go
- vendor/modules.txt
This pull request updates eclcloud to [v2.7.0](https://github.com/nttcom/eclcloud/releases/tag/v2.7.0)
> Update eclcloud to v2.7.0
